In [1]:
import pandas as pd
import requests 
import time
from sqlalchemy import *
import MySQLdb

In [2]:
# %%writefile ../db.ini
# [sql]
# public_ip = ...
# user = ...
# pw = ...
# [mongodb]
# user = ...
# pw = ...

Overwriting /home/ubuntu/db.ini

In [2]:
import configparser

In [3]:
config = configparser.ConfigParser()
config.read("../db.ini")
sql_datas = config["sql"]

> 크롤링하는 py파일에 sqlalchemy의 engine연결 후 df.to_sql() 시도\
**-> sql 내 테이블은 만들어졌으나 아래와 같은 에러메세지, 데이터 들어가지지않음**

> DB를 처음 만들때 default값이 레티나? 로 되어있어서 utf8로 해줘야 들어감(강사님)

In [6]:
# %load baemin_mart_delivery_goods.py

import pandas as pd
import requests 
import time
from sqlalchemy import *
import configparser

config = configparser.ConfigParser()
config.read("../db.ini")
sql_datas = config["sql"]

# 카테고리 수정 전(참고용)
# categories = {
#     100104 : "플라스틱용기",
#     100105 : "종이용기/박스",
#     100138 : "카페/음료용기",
#     100159 : "종이/비닐봉투",
#     100165 : "수저/위생용품",
#     100177 : "스티커/배너/포스터",
#     100184 : "포장재",
#     100188 : "기타가게용품",
# }

# 카테고리 수정 후 
categories = {
    100104 : "포장용품",
    100105 : "포장용품",
    100138 : "포장용품",
    100159 : "포장용품",
    100165 : "가게위생용품",
    100184 : "포장용품",
    100188 : "가게위생용품",
}


def baemin_items(category, page):
    url = "https://mart.baemin.com/api/v2/front/categories/goods/{}/paging?goodsSortType=BASIC&page={}".format(category, page)
    response = requests.get(url)
    elements = response.json()['data']['simpleGoodsDtoPage']['content']
    datas = []
    for element in elements:
        title = element['name']
        price = element['goodsPrice']
#         o_price = element['customerPrice']
        # 원인은 모르겠지만.. 100050/밀가루 쪽에서 에러남
        try :
            min_gram = element['sizeDesc']
        except:
            min_gram = "-"
        try:
            price_per_gram = element['priceDesc']
        except:
            price_per_gram = "-"
        link = "https://mart.baemin.com/goods/detail/" + str(element['id'])

        datas.append({
            "category": categories[category],
            "title" : title,
            "price" : price,
#             "o_price" : o_price,
            "min_gram" : min_gram,
            "price_per_gram" : price_per_gram,
            "link" : link,
        })
        
    return pd.DataFrame(datas)

dfs = []
for category in categories:
    print(categories[category])
    for page in range(12): # url에서 page가 0부터 시작
        print(page, end=" ")
        df = baemin_items(category, page)
        dfs.append(df)
    print()
    time.sleep(2)

# global gagong_df -> 파이썬 파일을 실행 했을 때 gagong_df가 나왔으면 좋겠음.. 
baemin_mart_delivery_goods_df = pd.concat(dfs)
baemin_mart_delivery_goods_df

# 아래와 같은 에러가 뜸. 무슨 뜻일까... sql에 table은 만들어 졌는데...
engine = create_engine("mysql://{}:{}@{}/test".format(sql_datas['user'], sql_datas['pw'], sql_datas['public_ip']))
baemin_mart_delivery_goods_df.to_sql(name="baemin_del_goods", con=engine, if_exists="replace")

# baemin_mart_delivery_goods_df.to_csv("baemin_mart_delivery_goods.csv", index=False, encoding="utf-8-sig")

# print("="*100)
# print("It's saved as baemin_mart_delivery_goods.csv file.")
# print("="*100)

포장용품
0 1 2 3 4 5 6 7 8 9 10 11
포장용품
0 1 2 3 4 5 6 7 8 9 10 11
포장용품
0 1 2 3 4 5 6 7 8 9 10 11
포장용품
0 1 2 3 4 5 6 7 8 9 10 11
가게위생용품
0 1 2 3 4 5 6 7 8 9 10 11
포장용품
0 1 2 3 4 5 6 7 8 9 10 11
가게위생용품
0 1 2 3 4 5 6 7 8 9 10 11

UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>

> MySQLdb의 connect를 사용하여 쿼리문을 execute 시도\
**-> sql에 데이터 들어감 확인**

> ### MySQLdb보다는 SQLAlchemy를 쓰는게 좋음
- 쿼리문을 안써도 되니까 코드의 길이가 줄어들음.
- 객체화 시킬 수 있음

In [7]:
%%writefile baemin_del_MySQLdb.py

import pandas as pd
import requests 
import time
from sqlalchemy import *
import MySQLdb
import configparser

config = configparser.ConfigParser()
config.read("../db.ini")
sql_datas = config["sql"]


# 카테고리 수정 전(참고용)
# categories = {
#     100104 : "플라스틱용기",
#     100105 : "종이용기/박스",
#     100138 : "카페/음료용기",
#     100159 : "종이/비닐봉투",
#     100165 : "수저/위생용품",
#     100177 : "스티커/배너/포스터",
#     100184 : "포장재",
#     100188 : "기타가게용품",
# }

# 카테고리 수정 후 
categories = {
    100104 : "포장용품",
    100105 : "포장용품",
    100138 : "포장용품",
    100159 : "포장용품",
    100165 : "가게위생용품",
    100184 : "포장용품",
    100188 : "가게위생용품",
}

db = MySQLdb.connect(
    sql_datas['public_ip'],  # database server public ip
    sql_datas['user'],           # user
    sql_datas['pw'],            # password
    "test",          # database name
    charset='utf8',
)
curs = db.cursor()
curs.execute('set names utf8')
db.commit

QUERY_1 = """
DROP DATABASE IF EXISTS baemin_db; 
CREATE DATABASE baemin_db DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

USE baemin_db;
DROP TABLE IF EXISTS baemin_db.baemin;
CREATE TABLE IF NOT EXISTS baemin_db.baemin(
    item_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    category VARCHAR(6),
    title VARCHAR(60),
    price INT,
    min_gram VARCHAR(30),
    price_per_gram VARCHAR(20),
    link VARCHAR(50),
    PRIMARY KEY(item_id)
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin
"""
curs.execute(QUERY_1)
db.commit

def baemin_items(category, page):
    url = "https://mart.baemin.com/api/v2/front/categories/goods/{}/paging?goodsSortType=BASIC&page={}".format(category, page)
    response = requests.get(url)
    elements = response.json()['data']['simpleGoodsDtoPage']['content']
    datas = []
    for element in elements:
        title = element['name']
        price = element['goodsPrice']
#         o_price = element['customerPrice']
        # 원인은 모르겠지만.. 100050/밀가루 쪽에서 에러남
        try :
            min_gram = element['sizeDesc']
        except:
            min_gram = "-"
        try:
            price_per_gram = element['priceDesc']
        except:
            price_per_gram = "-"
        link = "https://mart.baemin.com/goods/detail/" + str(element['id'])

        # SQL로 넣기
        QUERY_2 = """
        INSERT INTO baemin_db.baemin(
        category, title, price, min_gram, price_per_gram, link
        )
        VALUES(
        '%s', '%s', %d, '%s', '%s', '%s' 
        )
        """%(categories[category], title, price, min_gram, price_per_gram, link)
        curs.execute(QUERY_2)
        db.commit()
                
        # DF로 만들기
        datas.append({
            "category": categories[category],
            "title" : title,
            "price" : price,
#             "o_price" : o_price,
            "min_gram" : min_gram,
            "price_per_gram" : price_per_gram,
            "link" : link,
        })
        
    return pd.DataFrame(datas)

dfs = []
for category in categories:
    print(categories[category])
    for page in range(12): # url에서 page가 0부터 시작
        print(page, end=" ")
        df = baemin_items(category, page)
        dfs.append(df)
    print()
    time.sleep(2)

# global gagong_df -> 파이썬 파일을 실행 했을 때 gagong_df가 나왔으면 좋겠음.. 
baemin_mart_delivery_goods_df = pd.concat(dfs, ignore_index=True)
baemin_mart_delivery_goods_df

print("="*60)
print("Plz input 'baemin_mart_delivery_goods_df'")
print("="*60)



# engine = create_engine("mysql://root:dss@15.164.65.158/test")
# baemin_mart_delivery_goods_df.to_sql(name="baemin_del_goods", con=engine, if_exists="replace")

# baemin_mart_delivery_goods_df.to_csv("baemin_mart_delivery_goods.csv", index=False, encoding="utf-8-sig")

# print("="*100)
# print("It's saved as baemin_mart_delivery_goods.csv file.")
# print("="*100)

Writing baemin_del_MySQLdb.py

> sql 연결과 db, table 생성 테스트 해보기

In [10]:
db = MySQLdb.connect(
    sql_datas['public_ip'],  # database server public ip
    sql_datas['user'],           # user
    sql_datas['pw'],            # password
    "test",          # database name
    charset='utf8',
)
curs = db.cursor()
curs.execute('set names utf8')
db.commit

In [9]:
QUERY_1 = """
DROP DATABASE IF EXISTS baemin_db; 
CREATE DATABASE baemin_db DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

USE baemin_db;
DROP TABLE IF EXISTS baemin_db.baemin;
CREATE TABLE IF NOT EXISTS baemin_db.baemin(
    item_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    category VARCHAR(6),
    title VARCHAR(60),
    price INT,
    min_gram VARCHAR(30),
    price_per_gram VARCHAR(20),
    link VARCHAR(50),
    PRIMARY KEY(item_id)
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin
"""

In [10]:
curs.execute(QUERY_1)
db.commit

In [ ]:
# QUERY_2 = """
# INSERT INTO baemin_db.baemin(
# )
# """

> 카테고리 2개만 우선 테스트 해보기

In [6]:
import pandas as pd
import requests 
import time
from sqlalchemy import *
import MySQLdb


# 카테고리 수정 전(참고용)
# categories = {
#     100104 : "플라스틱용기",
#     100105 : "종이용기/박스",
#     100138 : "카페/음료용기",
#     100159 : "종이/비닐봉투",
#     100165 : "수저/위생용품",
#     100177 : "스티커/배너/포스터",
#     100184 : "포장재",
#     100188 : "기타가게용품",
# }

# 카테고리 수정 후 
categories = {
    100104 : "포장용품",
    100105 : "포장용품",
}

db = MySQLdb.connect(
    sql_datas['public_ip'],  # database server public ip
    sql_datas['user'],           # user
    sql_datas['pw'],            # password
    "test",          # database name
    charset='utf8',
)
curs = db.cursor()
curs.execute('set names utf8')
db.commit

QUERY_1 = """
DROP DATABASE IF EXISTS baemin_db; 
CREATE DATABASE baemin_db DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

USE baemin_db;
DROP TABLE IF EXISTS baemin_db.baemin;
CREATE TABLE IF NOT EXISTS baemin_db.baemin(
    item_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    category VARCHAR(6),
    title VARCHAR(60),
    price INT,
    min_gram VARCHAR(30),
    price_per_gram VARCHAR(20),
    link VARCHAR(50),
    PRIMARY KEY(item_id)
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin
"""
curs.execute(QUERY_1)
db.commit

def baemin_items(category, page):
    url = "https://mart.baemin.com/api/v2/front/categories/goods/{}/paging?goodsSortType=BASIC&page={}".format(category, page)
    response = requests.get(url)
    elements = response.json()['data']['simpleGoodsDtoPage']['content']
    datas = []
    for element in elements:
        title = element['name']
        price = element['goodsPrice']
#         o_price = element['customerPrice']
        # 원인은 모르겠지만.. 100050/밀가루 쪽에서 에러남
        try :
            min_gram = element['sizeDesc']
        except:
            min_gram = "-"
        try:
            price_per_gram = element['priceDesc']
        except:
            price_per_gram = "-"
        link = "https://mart.baemin.com/goods/detail/" + str(element['id'])

        # SQL로 넣기
        QUERY_2 = """
        INSERT INTO baemin_db.baemin(
        category, title, price, min_gram, price_per_gram, link
        )
        VALUES(
        '%s', '%s', %d, '%s', '%s', '%s' 
        )
        """%(categories[category], title, price, min_gram, price_per_gram, link)
        curs.execute(QUERY_2)
        db.commit()
                
        # DF로 만들기
        datas.append({
            "category": categories[category],
            "title" : title,
            "price" : price,
#             "o_price" : o_price,
            "min_gram" : min_gram,
            "price_per_gram" : price_per_gram,
            "link" : link,
        })
        
    return pd.DataFrame(datas)

dfs = []
for category in categories:
    print(categories[category])
    for page in range(12): # url에서 page가 0부터 시작
        print(page, end=" ")
        df = baemin_items(category, page)
        dfs.append(df)
    print()
    time.sleep(2)

# global gagong_df -> 파이썬 파일을 실행 했을 때 gagong_df가 나왔으면 좋겠음.. 
baemin_mart_delivery_goods_df = pd.concat(dfs, ignore_index=True)
baemin_mart_delivery_goods_df

print("="*60)
print("Plz input 'baemin_mart_delivery_goods_df'")
print("="*60)



# engine = create_engine("mysql://root:dss@15.164.65.158/test")
# baemin_mart_delivery_goods_df.to_sql(name="baemin_del_goods", con=engine, if_exists="replace")

# baemin_mart_delivery_goods_df.to_csv("baemin_mart_delivery_goods.csv", index=False, encoding="utf-8-sig")

# print("="*100)
# print("It's saved as baemin_mart_delivery_goods.csv file.")
# print("="*100)

포장용품
0 1 2 3 4 5 6 7 8 9 10 11
포장용품
0 1 2 3 4 5 6 7 8 9 10 11
============================================================
Plz input 'baemin_mart_delivery_goods_df'
============================================================

In [10]:
baemin_mart_delivery_goods_df.tail()

,category,link,min_gram,price,price_per_gram,title
1509,포장용품,https://mart.baemin.com/goods/detail/14475,205Øx43(mm),125900,개당 252원 / 500ea,사탕수수 펄프용기(H-24oz/원형)
1510,포장용품,https://mart.baemin.com/goods/detail/14476,205Øx60(mm),130700,개당 262원 / 500ea,사탕수수 펄프용기(H-32oz/원형)
1511,포장용품,https://mart.baemin.com/goods/detail/14477,205Øx70(mm),140200,개당 281원 / 500ea,사탕수수 펄프용기(H-40oz/원형)
1512,포장용품,https://mart.baemin.com/goods/detail/14478,280x220x40(mm),60800,개당 304원 / 200ea,사탕수수 펄프용기(H-5칸도시락)
1513,포장용품,https://mart.baemin.com/goods/detail/14711,100x60x60(mm),34000,개당 85원 / 400ea,햄버거트레이-그리드

> ## 최종 파일

In [ ]:
# %load baemin_del_MySQLdb.py

import pandas as pd
import requests 
import time
from sqlalchemy import *
import MySQLdb
import configparser

config = configparser.ConfigParser()
config.read("../db.ini")
sql_datas = config["sql"]


# 카테고리 수정 전(참고용)
# categories = {
#     100104 : "플라스틱용기",
#     100105 : "종이용기/박스",
#     100138 : "카페/음료용기",
#     100159 : "종이/비닐봉투",
#     100165 : "수저/위생용품",
#     100177 : "스티커/배너/포스터",
#     100184 : "포장재",
#     100188 : "기타가게용품",
# }

# 카테고리 수정 후 
categories = {
    100104 : "포장용품",
    100105 : "포장용품",
    100138 : "포장용품",
    100159 : "포장용품",
    100165 : "가게위생용품",
    100184 : "포장용품",
    100188 : "가게위생용품",
}

db = MySQLdb.connect(
    sql_datas['public_ip'],  # database server public ip
    sql_datas['user'],           # user
    sql_datas['pw'],            # password
    "test",          # database name
    charset='utf8',
)
curs = db.cursor()
curs.execute('set names utf8')
db.commit

QUERY_1 = """
DROP DATABASE IF EXISTS baemin_db; 
CREATE DATABASE baemin_db DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

USE baemin_db;
DROP TABLE IF EXISTS baemin_db.baemin;
CREATE TABLE IF NOT EXISTS baemin_db.baemin(
    item_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    category VARCHAR(6),
    title VARCHAR(60),
    price INT,
    min_gram VARCHAR(30),
    price_per_gram VARCHAR(20),
    link VARCHAR(50),
    PRIMARY KEY(item_id)
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin
"""
curs.execute(QUERY_1)
db.commit

def baemin_items(category, page):
    url = "https://mart.baemin.com/api/v2/front/categories/goods/{}/paging?goodsSortType=BASIC&page={}".format(category, page)
    response = requests.get(url)
    elements = response.json()['data']['simpleGoodsDtoPage']['content']
    datas = []
    for element in elements:
        title = element['name']
        price = element['goodsPrice']
#         o_price = element['customerPrice']
        # 원인은 모르겠지만.. 100050/밀가루 쪽에서 에러남
        try :
            min_gram = element['sizeDesc']
        except:
            min_gram = "-"
        try:
            price_per_gram = element['priceDesc']
        except:
            price_per_gram = "-"
        link = "https://mart.baemin.com/goods/detail/" + str(element['id'])

        # SQL로 넣기
        QUERY_2 = """
        INSERT INTO baemin_db.baemin(
        category, title, price, min_gram, price_per_gram, link
        )
        VALUES(
        '%s', '%s', %d, '%s', '%s', '%s' 
        )
        """%(categories[category], title, price, min_gram, price_per_gram, link)
        curs.execute(QUERY_2)
        db.commit()
                
        # DF로 만들기
        datas.append({
            "category": categories[category],
            "title" : title,
            "price" : price,
#             "o_price" : o_price,
            "min_gram" : min_gram,
            "price_per_gram" : price_per_gram,
            "link" : link,
        })
        
    return pd.DataFrame(datas)

dfs = []
for category in categories:
    print(categories[category])
    for page in range(12): # url에서 page가 0부터 시작
        print(page, end=" ")
        df = baemin_items(category, page)
        dfs.append(df)
    print()
    time.sleep(2)

# global gagong_df -> 파이썬 파일을 실행 했을 때 gagong_df가 나왔으면 좋겠음.. 
baemin_mart_delivery_goods_df = pd.concat(dfs, ignore_index=True)
baemin_mart_delivery_goods_df

print("="*60)
print("Plz input 'baemin_mart_delivery_goods_df'")
print("="*60)



# engine = create_engine("mysql://root:dss@15.164.65.158/test")
# baemin_mart_delivery_goods_df.to_sql(name="baemin_del_goods", con=engine, if_exists="replace")

# baemin_mart_delivery_goods_df.to_csv("baemin_mart_delivery_goods.csv", index=False, encoding="utf-8-sig")

# print("="*100)
# print("It's saved as baemin_mart_delivery_goods.csv file.")
# print("="*100)

In [12]:
baemin_mart_delivery_goods_df.tail()

,category,link,min_gram,price,price_per_gram,title
2388,가게위생용품,https://mart.baemin.com/goods/detail/8833,2L,1050,"개당 1,050원 / 1ea",[든든]리오 락스 2L
2389,가게위생용품,https://mart.baemin.com/goods/detail/8828,2ea,1980,"개당 1,980원 / 1ea",[든든]스카치브라이트 수세미(다목적용_청색) 2 개
2390,가게위생용품,https://mart.baemin.com/goods/detail/8826,3ea,770,개당 770원 / 1ea,[든든]크린업 부직포행주(삼색_38*38cm) 3 개
2391,가게위생용품,https://mart.baemin.com/goods/detail/8823,2ea,1170,"개당 1,170원 / 1ea",[든든]크린업 스폰지수세미(15*9*3cm) 2 개
2392,가게위생용품,https://mart.baemin.com/goods/detail/8819,2ea,700,개당 700원 / 1ea,[든든]크린업 은사수세미(18*14cm) 2 개